### ISSUE TITLE
M20 Collection not Draftable

### ISSUE THREAD

**Issue by tylermurry** [jjallaire/draftpod#58] opened 2019-10-13 19:38 UTC
I have a collection of 405 cards that was formed by opening 27 boosters of M20, however I am not able to use this cardpool to start a draft and get the following error:

![image](https://user-images.githubusercontent.com/8295149/66720793-fa4a6d80-edc6-11e9-9e94-0b4ff709ec7e.png)

Here is the CSV export from deckbox.org:

```csv
Count,Tradelist Count,Name,Edition,Card Number,Condition,Language,Foil,Signed,Artist Proof,Altered Art,Misprint,Promo,Textless,My Price
6,0,Bone Splinters,Core Set 2020,92,Near Mint,English,,,,,,,,
5,0,Fire Elemental,Core Set 2020,138,Near Mint,English,,,,,,,,
4,0,Anticipate,Core Set 2020,45,Near Mint,English,,,,,,,,
4,0,Battalion Foot Soldier,Core Set 2020,7,Near Mint,English,,,,,,,,
4,0,Bone to Ash,Core Set 2020,48,Near Mint,English,,,,,,,,
4,0,Centaur Courser,Core Set 2020,168,Near Mint,English,,,,,,,,
4,0,Convolute,Core Set 2020,55,Near Mint,English,,,,,,,,
4,0,Daggersail Aeronaut,Core Set 2020,133,Near Mint,English,,,,,,,,
4,0,Disenchant,Core Set 2020,14,Near Mint,English,,,,,,,,
4,0,Fortress Crab,Core Set 2020,60,Near Mint,English,,,,,,,,
4,0,Frost Lynx,Core Set 2020,62,Near Mint,English,,,,,,,,
4,0,Gorging Vulture,Core Set 2020,102,Near Mint,English,,,,,,,,
4,0,Griffin Sentinel,Core Set 2020,21,Near Mint,English,,,,,,,,
4,0,Growth Cycle,Core Set 2020,175,Near Mint,English,,,,,,,,
4,0,Heart-Piercer Bow,Core Set 2020,228,Near Mint,English,,,,,,,,
4,0,Maniacal Rage,Core Set 2020,149,Near Mint,English,,,,,,,,
4,0,Prismite,Core Set 2020,235,Near Mint,English,,,,,,,,
4,0,Rabid Bite,Core Set 2020,190,Near Mint,English,,,,,,,,
4,0,Silverback Shaman,Core Set 2020,195,Near Mint,English,,,,,,,,
4,0,Winged Words,Core Set 2020,80,Near Mint,English,,,,,,,,
3,0,Aerial Assault,Core Set 2020,1,Near Mint,English,,,,,,,,
3,0,Ancestral Blade,Core Set 2020,3,Near Mint,English,,,,,,,,
3,0,Angelic Gift,Core Set 2020,5,Near Mint,English,,,,,,,,
3,0,Bladebrand,Core Set 2020,86,Near Mint,English,,,,,,,,
3,0,Chandra's Embercat,Core Set 2020,129,Near Mint,English,,,,,,,,
3,0,Chandra's Outrage,Core Set 2020,130,Near Mint,English,,,,,,,,
3,0,Cloudkin Seer,Core Set 2020,54,Near Mint,English,,,,,,,,
3,0,Dawning Angel,Core Set 2020,11,Near Mint,English,,,,,,,,
3,0,Epicure of Blood,Core Set 2020,99,Near Mint,English,,,,,,,,
3,0,Faerie Miscreant,Core Set 2020,58,Near Mint,English,,,,,,,,
3,0,Fathom Fleet Cutthroat,Core Set 2020,100,Near Mint,English,,,,,,,,
3,0,Feral Abomination,Core Set 2020,101,Near Mint,English,,,,,,,,
3,0,Ferocious Pup,Core Set 2020,171,Near Mint,English,,,,,,,,
3,0,Frilled Sea Serpent,Core Set 2020,61,Near Mint,English,,,,,,,,
3,0,Gauntlets of Light,Core Set 2020,17,Near Mint,English,,,,,,,,
3,0,Goblin Smuggler,Core Set 2020,144,Near Mint,English,,,,,,,,
3,0,Gods Willing,Core Set 2020,19,Near Mint,English,,,,,,,,
3,0,Greenwood Sentinel,Core Set 2020,174,Near Mint,English,,,,,,,,
3,0,Inspired Charge,Core Set 2020,24,Near Mint,English,,,,,,,,
3,0,Inspiring Captain,Core Set 2020,25,Near Mint,English,,,,,,,,
3,0,Leafkin Druid,Core Set 2020,178,Near Mint,English,,,,,,,,
3,0,Metropolis Sprite,Core Set 2020,66,Near Mint,English,,,,,,,,
3,0,Mind Rot,Core Set 2020,108,Near Mint,English,,,,,,,,
3,0,Murder,Core Set 2020,109,Near Mint,English,,,,,,,,
3,0,Netcaster Spider,Core Set 2020,184,Near Mint,English,,,,,,,,
3,0,Plummet,Core Set 2020,188,Near Mint,English,,,,,,,,
3,0,Raise the Alarm,Core Set 2020,34,Near Mint,English,,,,,,,,
3,0,Reckless Air Strike,Core Set 2020,154,Near Mint,English,,,,,,,,
3,0,Ripscale Predator,Core Set 2020,157,Near Mint,English,,,,,,,,
3,0,Sage's Row Denizen,Core Set 2020,73,Near Mint,English,,,,,,,,
3,0,Scorch Spitter,Core Set 2020,159,Near Mint,English,,,,,,,,
3,0,Sedge Scorpion,Core Set 2020,192,Near Mint,English,,,,,,,,
3,0,Soul Salvage,Core Set 2020,116,Near Mint,English,,,,,,,,
3,0,Squad Captain,Core Set 2020,38,Near Mint,English,,,,,,,,
3,0,Steadfast Sentry,Core Set 2020,40,Near Mint,English,,,,,,,,
3,0,Tectonic Rift,Core Set 2020,161,Near Mint,English,,,,,,,,
3,0,Thicket Crasher,Core Set 2020,196,Near Mint,English,,,,,,,,
3,0,Unholy Indenture,Core Set 2020,119,Near Mint,English,,,,,,,,
3,0,Wind-Scarred Crag,Core Set 2020,260,Near Mint,English,,,,,,,,
3,0,Wolfkin Bond,Core Set 2020,203,Near Mint,English,,,,,,,,
3,0,Yoked Ox,Core Set 2020,41,Near Mint,English,,,,,,,,
3,0,Zephyr Charge,Core Set 2020,82,Near Mint,English,,,,,,,,
2,0,Air Elemental,Core Set 2020,44,Near Mint,English,,,,,,,,
2,0,Anvilwrought Raptor,Core Set 2020,221,Near Mint,English,,,,,,,,
2,0,Audacious Thief,Core Set 2020,84,Near Mint,English,,,,,,,,
2,0,Barony Vampire,Core Set 2020,85,Near Mint,English,,,,,,,,
2,0,Befuddle,Core Set 2020,47,Near Mint,English,,,,,,,,
2,0,Blood Burglar,Core Set 2020,88,Near Mint,English,,,,,,,,
2,0,Bloodfell Caves,Core Set 2020,242,Near Mint,English,,,,,,,,
2,0,Bloodsoaked Altar,Core Set 2020,90,Near Mint,English,,,,,,,,
2,0,Boneclad Necromancer,Core Set 2020,93,Near Mint,English,,,,,,,,
2,0,Boreal Elemental,Core Set 2020,49,Near Mint,English,,,,,,,,
2,0,Brightwood Tracker,Core Set 2020,166,Near Mint,English,,,,,,,,
2,0,Brineborn Cutthroat,Core Set 2020,50,Near Mint,English,,,,,,,,
2,0,Chandra's Regulator,Core Set 2020,131,Near Mint,English,,,,,,,,
2,0,Corpse Knight,Core Set 2020,206,Near Mint,English,,,,,,,,
2,0,Daybreak Chaplain,Core Set 2020,12,Near Mint,English,,,,,,,,
2,0,Destructive Digger,Core Set 2020,134,Near Mint,English,,,,,,,,
2,0,Devout Decree,Core Set 2020,13,Near Mint,English,,,,,,,,
2,0,Dismal Backwater,Core Set 2020,245,Near Mint,English,,,,,,,,
2,0,Drawn from Dreams,Core Set 2020,56,Near Mint,English,,,,,,,,
2,0,Duress,Core Set 2020,97,Near Mint,English,,,,,,,,
2,0,Feral Invocation,Core Set 2020,170,Near Mint,English,,,,,,,,
2,0,Flame Sweep,Core Set 2020,139,Near Mint,English,,,,,,,,
2,0,Gift of Paradise,Core Set 2020,173,Near Mint,English,,,,,,,,
2,0,Glaring Aegis,Core Set 2020,18,Near Mint,English,,,,,,,,
2,0,Glint-Horn Buccaneer,Core Set 2020,141,Near Mint,English,,,,,,,,
2,0,Goblin Bird-Grabber,Core Set 2020,142,Near Mint,English,,,,,,,,
2,0,Griffin Protector,Core Set 2020,20,Near Mint,English,,,,,,,,
2,0,Healer of the Glade,Core Set 2020,176,Near Mint,English,,,,,,,,
2,0,Herald of the Sun,Core Set 2020,23,Near Mint,English,,,,,,,,
2,0,Infuriate,Core Set 2020,145,Near Mint,English,,,,,,,,
2,0,Keldon Raider,Core Set 2020,146,Near Mint,English,,,,,,,,
2,0,Lavakin Brawler,Core Set 2020,147,Near Mint,English,,,,,,,,
2,0,Loyal Pegasus,Core Set 2020,28,Near Mint,English,,,,,,,,
2,0,Manifold Key,Core Set 2020,230,Near Mint,English,,,,,,,,
2,0,Marauder's Axe,Core Set 2020,231,Near Mint,English,,,,,,,,
2,0,Mask of Immolation,Core Set 2020,151,Near Mint,English,,,,,,,,
2,0,Might of the Masses,Core Set 2020,182,Near Mint,English,,,,,,,,
2,0,Moorland Inquisitor,Core Set 2020,31,Near Mint,English,,,,,,,,
2,0,Natural End,Core Set 2020,183,Near Mint,English,,,,,,,,
2,0,Negate,Core Set 2020,69,Near Mint,English,,,,,,,,
2,0,Noxious Grasp,Core Set 2020,110,Near Mint,English,,,,,,,,
2,0,Pacifism,Core Set 2020,32,Near Mint,English,,,,,,,,
2,0,Pack Mastiff,Core Set 2020,152,Near Mint,English,,,,,,,,
2,0,Pulse of Murasa,Core Set 2020,189,Near Mint,English,,,,,,,,
2,0,Reduce to Ashes,Core Set 2020,155,Near Mint,English,,,,,,,,
2,0,Sanitarium Skeleton,Core Set 2020,112,Near Mint,English,,,,,,,,
2,0,Scampering Scorcher,Core Set 2020,158,Near Mint,English,,,,,,,,
2,0,Scholar of the Ages,Core Set 2020,74,Near Mint,English,,,,,,,,
2,0,Shared Summons,Core Set 2020,193,Near Mint,English,,,,,,,,
2,0,Shock,Core Set 2020,160,Near Mint,English,,,,,,,,
2,0,Sleep Paralysis,Core Set 2020,75,Near Mint,English,,,,,,,,
2,0,Stone Golem,Core Set 2020,240,Near Mint,English,,,,,,,,
2,0,Swiftwater Cliffs,Core Set 2020,252,Near Mint,English,,,,,,,,
2,0,Tomebound Lich,Core Set 2020,219,Near Mint,English,,,,,,,,
2,0,Tranquil Cove,Core Set 2020,259,Near Mint,English,,,,,,,,
2,0,Undead Servant,Core Set 2020,118,Near Mint,English,,,,,,,,
2,0,Unsummon,Core Set 2020,78,Near Mint,English,,,,,,,,
2,0,Vial of Dragonfire,Core Set 2020,241,Near Mint,English,,,,,,,,
2,0,Vorstclaw,Core Set 2020,201,Near Mint,English,,,,,,,,
1,0,Act of Treason,Core Set 2020,124,Near Mint,English,,,,,,,,
1,0,Aether Gust,Core Set 2020,42,Near Mint,English,,,,,,,,
1,0,Agonizing Syphon,Core Set 2020,83,Near Mint,English,,,,,,,,
1,0,"Atemsis, All-Seeing",Core Set 2020,46,Near Mint,English,,,,,,,,
1,0,Bag of Holding,Core Set 2020,222,Near Mint,English,,,,,,,,
1,0,Barkhide Troll,Core Set 2020,165,Near Mint,English,,,,,,,,
1,0,Blood for Bones,Core Set 2020,89,Near Mint,English,,,,,,,,
1,0,Blossoming Sands,Core Set 2020,243,Near Mint,English,,,,,,,,
1,0,Captivating Gyre,Core Set 2020,51,Near Mint,English,,,,,,,,
1,0,Cerulean Drake,Core Set 2020,53,Near Mint,English,,,,,,,,
1,0,Chandra's Spitfire,Core Set 2020,132,Near Mint,English,,,,,,,,
1,0,"Chandra, Acolyte of Flame",Core Set 2020,126,Near Mint,English,,,,,,,,
1,0,Colossus Hammer,Core Set 2020,223,Near Mint,English,,,,,,,,
1,0,Creeping Trailblazer,Core Set 2020,207,Near Mint,English,,,,,,,,
1,0,Cryptic Caves,Core Set 2020,244,Near Mint,English,,,,,,,,
1,0,Diamond Knight,Core Set 2020,224,Near Mint,English,,,,,,,,
1,0,Diviner's Lockbox,Core Set 2020,225,Near Mint,English,,,,,,,,
1,0,"Drakuseth, Maw of Flames",Core Set 2020,136,Near Mint,English,,,,,,,,
1,0,Ember Hauler,Core Set 2020,137,Near Mint,English,,,,,,,,
1,0,Embodiment of Agonies,Core Set 2020,98,Near Mint,English,,,,,,,,
1,0,Empyrean Eagle,Core Set 2020,208,Near Mint,English,,,,,,,,
1,0,Eternal Isolation,Core Set 2020,15,Near Mint,English,,,,,,,,
1,0,Field of the Dead,Core Set 2020,247,Near Mint,English,,,,,,,,
1,0,Fry,Core Set 2020,140,Near Mint,English,,,,,,,,
1,0,Goblin Ringleader,Core Set 2020,143,Near Mint,English,,,,,,,,
1,0,Grafdigger's Cage,Core Set 2020,227,Near Mint,English,,,,,,,,
1,0,Gravedigger,Core Set 2020,103,Near Mint,English,,,,,,,,
1,0,Gruesome Scourger,Core Set 2020,104,Near Mint,English,,,,,,,,
1,0,Hanged Executioner,Core Set 2020,22,Near Mint,English,,,,,,,,
1,0,Hard Cover,Core Set 2020,63,Near Mint,English,,,,,,,,
1,0,Howling Giant,Core Set 2020,177,Near Mint,English,,,,,,,,
1,0,Ironroot Warlord,Core Set 2020,209,Near Mint,English,,,,,,,,
1,0,Jungle Hollow,Core Set 2020,248,Near Mint,English,,,,,,,,
1,0,"Kykar, Wind's Fury",Core Set 2020,212,Near Mint,English,,,,,,,,
1,0,Leyline of Abundance,Core Set 2020,179,Near Mint,English,,,,,,,,
1,0,Leyline of Combustion,Core Set 2020,148,Near Mint,English,,,,,,,,
1,0,Leyline of Sanctity,Core Set 2020,26,Near Mint,English,,,,,,,,
1,0,Leyline of the Void,Core Set 2020,107,Near Mint,English,,,,,,,,
1,0,Lightning Stormkin,Core Set 2020,213,Near Mint,English,,,,,,,,
1,0,Lotus Field,Core Set 2020,249,Near Mint,English,,,,,,,,
1,0,Mammoth Spider,Core Set 2020,181,Near Mint,English,,,,,,,,
1,0,Masterful Replication,Core Set 2020,65,Near Mint,English,,,,,,,,
1,0,Moat Piranhas,Core Set 2020,67,Near Mint,English,,,,,,,,
1,0,Moldervine Reclamation,Core Set 2020,214,Near Mint,English,,,,,,,,
1,0,Moment of Heroism,Core Set 2020,30,Near Mint,English,,,,,,,,
1,0,Nightpack Ambusher,Core Set 2020,185,Near Mint,English,,,,,,,,
1,0,Octoprophet,Core Set 2020,70,Near Mint,English,,,,,,,,
1,0,Ogre Siegebreaker,Core Set 2020,215,Near Mint,English,,,,,,,,
1,0,Overcome,Core Set 2020,186,Near Mint,English,,,,,,,,
1,0,Portal of Sanctuary,Core Set 2020,71,Near Mint,English,,,,,,,,
1,0,Rapacious Dragon,Core Set 2020,153,Near Mint,English,,,,,,,,
1,0,Renowned Weaponsmith,Core Set 2020,72,Near Mint,English,,,,,,,,
1,0,Risen Reef,Core Set 2020,217,Near Mint,English,,,,,,,,
1,0,Rugged Highlands,Core Set 2020,250,Near Mint,English,,,,,,,,
1,0,Rule of Law,Core Set 2020,35,Near Mint,English,,,,,,,,
1,0,Salvager of Ruin,Core Set 2020,237,Near Mint,English,,,,,,,,
1,0,Scheming Symmetry,Core Set 2020,113,Near Mint,English,,,,,,,,
1,0,Scuttlemutt,Core Set 2020,238,Near Mint,English,,,,,,,,
1,0,Season of Growth,Core Set 2020,191,Near Mint,English,,,,,,,,
1,0,Skyknight Vanguard,Core Set 2020,218,Near Mint,English,,,,,,,,
1,0,Sorcerer of the Fang,Core Set 2020,114,Near Mint,English,,,,,,,,
1,0,Soulmender,Core Set 2020,37,Near Mint,English,,,,,,,,
1,0,Spectral Sailor,Core Set 2020,76,Near Mint,English,,,,,,,,
1,0,Steel Overseer,Core Set 2020,239,Near Mint,English,,,,,,,,
1,0,Tale's End,Core Set 2020,77,Near Mint,English,,,,,,,,
1,0,Temple of Malady,Core Set 2020,254,Near Mint,English,,,,,,,,
1,0,Temple of Mystery,Core Set 2020,255,Near Mint,English,,,,,,,,
1,0,Temple of Triumph,Core Set 2020,257,Near Mint,English,,,,,,,,
1,0,Thought Distortion,Core Set 2020,117,Near Mint,English,,,,,,,,
1,0,Thrashing Brontodon,Core Set 2020,197,Near Mint,English,,,,,,,,
1,0,Uncaged Fury,Core Set 2020,163,Near Mint,English,,,,,,,,
1,0,Vampire of the Dire Moon,Core Set 2020,120,Near Mint,English,,,,,,,,
1,0,Vengeful Warchief,Core Set 2020,121,Near Mint,English,,,,,,,,
1,0,Voracious Hydra,Core Set 2020,200,Near Mint,English,,,,,,,,
1,0,Warden of Evos Isle,Core Set 2020,79,Near Mint,English,,,,,,,,
1,0,Wolfrider's Saddle,Core Set 2020,204,Near Mint,English,,,,,,,,
1,0,Woodland Champion,Core Set 2020,205,Near Mint,English,,,,,,,,
1,0,Yarok's Fenlurker,Core Set 2020,123,Near Mint,English,,,,,,,,
```

**Comment by jjallaire** [comment] 2019-10-13 19:43
27 boosters from M20 gives me a very strong clue as to what's going on here: I think you aren't getting enough dual lands. You can see here that we add a dual land to the pack for ~ 5 out of every 12 packs: https://github.com/jjallaire/draftpod/blob/master/src/store/modules/draft/set/set-m20.js#L23-L27.

This is random though, so your 27 packs might have had less dual lands than normal (making it tough to get enough in a pool). If you replace that block with:

```js
return cards.concat(selectCards(filters.basicLand, 1));
```

My guess is that things will work.

That said, I think we might need to be a bit more forgiving here and just fill in with basic lands.

**Comment by jjallaire** [comment] 2019-10-13 19:48
I made that change and it doesn't fix it, so perhaps we're somehow short of commons. In any case we should still be able to handle this scenario. Will investigate further.

**Comment by jjallaire** [comment] 2019-10-13 20:01
I'm wondering if maybe the issue is that there are no basic lands in the cardpool? Most of the time you don't need basics in the cardpool but in the case of M20 you do since they are included in packs (those that don't have dual lands)

**Comment by tylermurry** [comment] 2019-10-13 20:04
I thought the same thing and added 100 of each basic land just to be sure.
No luck. I also tried adding 50 of every card instead of the current count
which gave me 10k cards in the pool. No luck.

I will say that it's as if the engine didn't recognize that I added basics.
It still counted them as 405 cards with 500 extra basics.

[image: image.png]

**Comment by tylermurry** [comment] 2019-10-13 20:08
As I was stepping through in Chrome, I noticed that some packs only had 14
cards and not 15 so the basic land theory seems sound. Investigating on my
end as well.

Tyler

**Comment by jjallaire** [comment] 2019-10-13 20:14
I think we needed 2 fixes here:

1) Be more forgiving if there aren't enough dual lands (since it's random, you might not see this error every time but it would probably come up here and there w/ a 27 pack pool). That change is here: https://github.com/jjallaire/draftpod/commit/aa5b626b7821d90e05fe3e3301b929afba62cf96

2) Add the basics to the pool. If you add this to the end of your CSV then things should work correctly (they do on my end):

```
4,0,Plains,Core Set 2020,261,Near Mint,English,,,,,,,,
4,0,Plains,Core Set 2020,262,Near Mint,English,,,,,,,,
4,0,Plains,Core Set 2020,263,Near Mint,English,,,,,,,,
4,0,Plains,Core Set 2020,264,Near Mint,English,,,,,,,,
4,4,Island,Core Set 2020,265,Near Mint,English,,,,,,,,
4,4,Island,Core Set 2020,266,Near Mint,English,,,,,,,,
4,4,Island,Core Set 2020,267,Near Mint,English,,,,,,,,
4,4,Island,Core Set 2020,268,Near Mint,English,,,,,,,,
4,0,Mountain,Core Set 2020,273,Near Mint,English,,,,,,,,
4,0,Mountain,Core Set 2020,274,Near Mint,English,,,,,,,,
4,0,Mountain,Core Set 2020,275,Near Mint,English,,,,,,,,
4,0,Mountain,Core Set 2020,276,Near Mint,English,,,,,,,,
4,4,Swamp,Core Set 2020,269,Near Mint,English,,,,,,,,
4,4,Swamp,Core Set 2020,270,Near Mint,English,,,,,,,,
4,4,Swamp,Core Set 2020,271,Near Mint,English,,,,,,,,
4,4,Swamp,Core Set 2020,272,Near Mint,English,,,,,,,,
4,4,Forest,Core Set 2020,277,Near Mint,English,,,,,,,,
4,4,Forest,Core Set 2020,278,Near Mint,English,,,,,,,,
4,4,Forest,Core Set 2020,279,Near Mint,English,,,,,,,,
4,4,Forest,Core Set 2020,280,Near Mint,English,,,,,,,,
```

I still think that this will be a common source of error/frustration, so we should probably automatically add the lands if they aren't there.

**Comment by tylermurry** [comment] 2019-10-13 20:23
Bingo, yep I think that's the right fix too. Shouldn't have to have basics
in the collection to smooth it over so I like that. What does your CI/CD
process look like? Is that change something that will go in soon?

I appreciate you hoping on that so quickly! Again, if you need any
assistance in the future I would be happy to help out where I can.

Thanks!
Tyler

**Comment by jjallaire** [comment] 2019-10-13 20:43
Commits to master are deployed within a few minutes to https://master.draftpod.org. The production branch deploys to https://draftpod.org (I have already merged this change to production so it should be available both places).

**Comment by tylermurry** [comment] 2019-10-13 20:45
Dope. Nice setup!

Just submitted a feature request as well. Love the site!

Thanks,
Tyler

**Comment by jjallaire** [comment] 2019-10-14 12:07
This commit should ensure that a cardpool like the one you originally uploaded will still work fine (we just automatically provide 10x the basics for sets that use basics in their booster packs): https://github.com/jjallaire/draftpod/commit/12ba39038ce74c72d832fc9340ed42bd5d767fbe

**Closed by jjallaire** 2019-10-14 12:07 UTC
